portfolio_site/models.py
from enum import unique
from portfolio_site import db
from datetime import datetime

class EmailLeads(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    date = db.Column(db.DateTime, default=datetime.utcnow)
    email = db.Column(db.String(70), unique=True, nullable=False)

    def __repr__(self):
        return f"Email: {self.email}, date_added: {self.date}"

class Portfolio(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(50), nullable=False, unique=True)
    website_url = db.Column(db.String(200), nullable=False, unique=True)
    web_icon_url = db.Column(db.String(400), nullable=True)
    date_completed = db.Column(db.DateTime, default=datetime.utcnow)
    technology_used = db.Column(db.String(100), nullable=True)
    client_name = db.Column(db.String(30), nullable=True)
    source = db.Column(db.String(50), nullable=True)
    tags = db.Column(db.String(50), nullable=True)


    def __repr__(self):
        return f"url: {self.website_url}, client: {self.client_name}, source: {self.source}"


class OtherPortfolio(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(50), nullable=False, unique=True)
    work_type = db.Column(db.String(50), nullable=False, unique=False)


    def __repr__(self):
        return f"{self.name}, type: {self.work_type}"

portfolio_site/__init__.py
from flask import Flask, render_template
from flask_mail import Mail
from portfolio_site.config import Config
from flask_sqlalchemy import SQLAlchemy
from flask_admin import Admin

mail = Mail()
db = SQLAlchemy()
admin = Admin()

def create_app():
    app = Flask(__name__)
    app.config.from_object(Config)

    mail.init_app(app)
    db.init_app(app)
    admin.init_app(app)

    from portfolio_site.admin import myadmin
    app.register_blueprint(myadmin)

    from portfolio_site.main.routes import main
    app.register_blueprint(main)

    from portfolio_site.quote.routes import quote
    app.register_blueprint(quote)

    return app

portfolio_site/admin/__init__.py
from flask import Blueprint


myadmin = Blueprint('myadmin', __name__)

from portfolio_site.admin.routes import *

portfolio_site/admin/routes.py
from portfolio_site.models import Portfolio
from portfolio_site import admin
from flask_admin.contrib.sqla import ModelView
from portfolio_site.models import Portfolio, EmailLeads
from portfolio_site import db


admin.add_view(ModelView(Portfolio, db.session))
admin.add_view(ModelView(EmailLeads, db.session))

portfolio_site/main/routes.py
from flask import Blueprint, render_template, request, redirect, url_for
from portfolio_site import mail
from flask_mail import Message
from sqlalchemy import desc
from portfolio_site.models import *

main = Blueprint('main', __name__)

@main.route('/')
def home():
    return render_template("index.html")

@main.route('/web_development')
def web_development():
    return render_template("sections/services_page/web_development.html")

@main.route('/web_scraping')
def web_scraping():
    return render_template("sections/services_page/web_scraping.html")

@main.route('/ecommerce')
def ecommerce():
    return render_template("sections/services_page/ecommerce.html")

@main.route('/api')
def api():
    return render_template("sections/services_page/api.html")

@main.route('/portfolio')
def portfolio():
    portfolio_list = Portfolio.query.order_by(desc("id")).all()
    return render_template('sections/portfolio.html', portfolio_list=portfolio_list)

@main.route('/contact')
def contact():
    return render_template("sections/contact.html")

@main.route('/email', methods=["POST"])
def email():
    name = request.json['name']
    email = request.json['email']
    subject = request.json['subject']
    message = request.json['message']
    form_msg = Message(subject + f" ({email})", sender=email, 
                            recipients=['faizahmed11234@gmail.com', 'admin@faiz4work.com'], 
                            body=message)

    try:
        mail.send(form_msg)
        print("Email sent!")
    except:
        print("Email is not sent due to some reasons")
    return "done"

portfolio_site/quote/routes.py
from flask import Blueprint
from flask.templating import render_template

quote = Blueprint("quote", __name__)

@quote.route('/quote')
def quote_page():
    return render_template("quote/quote_form.html")

portfolio_site/templates/index.html
{% extends "layout.html" %}
{% block body %}


  <!-- ======= Hero Section ======= -->
  <section id="hero" class="d-flex align-items-center">

    <div class="container">
      <div class="row">
        <div class="col-lg-6 pt-5 pt-lg-0 order-2 order-lg-1 d-flex flex-column justify-content-center">
          <h1 data-aos="fade-up">Grow your business with Me.</h1>
          <h2 data-aos="fade-up" data-aos-delay="400">I am a freelancer and providing Website Development, Web designing, Web Scraping, Web Automation and much more.</h2>
          <div data-aos="fade-up" data-aos-delay="800">
            <a href="{{ url_for('quote.quote_page') }}" class="btn-get-started scrollto">Get A Quote</a>
            <a href="{{ url_for('main.portfolio') }}" class="btn-get-started scrollto">See Portfolio</a>
          </div>
        </div>
        <div class="col-lg-6 order-1 order-lg-2 hero-img" data-aos="fade-left" data-aos-delay="200">
          <img src="{{ url_for('static', filename='img/hero-img.png') }}" class="img-fluid animated" alt="">
        </div>
      </div>
    </div>

  </section><!-- End Hero -->

  <main id="main">


    <!-- ======= Counts Section ======= -->
    <section id="counts" class="counts">
      <div class="container">

        <div class="row">
          <div class="image col-xl-5 d-flex align-items-stretch justify-content-center justify-content-xl-start" data-aos="fade-right" data-aos-delay="150">
            <img src="{{ url_for('static', filename='img/about.jpg') }}" alt="" class="img-fluid">
          </div>

          <div id="about" class="col-xl-7 d-flex align-items-stretch pt-4 pt-xl-0" data-aos="fade-left" data-aos-delay="300">
            <div class="content d-flex flex-column justify-content-center">
              <div class="row bg-danger text-light p-4 mt-4" >
                <h2>About Me</h2>
                <p>I am faiz ahmed, a python developer. i am offering services of
                  web development, web scraping and web automation. I have 5 years of
                  experience and working from different market places like Fiverr.com,
                  Guru.com, Upwork.com.
                </p>
              </div>
            </div><!-- End .content-->
          </div>
        </div>

      </div>
    </section><!-- End Counts Section -->

   {% include "sections/services_page/services.html" %}

    <!-- ======= Testimonials Section ======= -->
    <section id="testimonials" class="testimonials section-bg d-none">
      <div class="container">

        <div class="section-title" data-aos="fade-up">
          <h2>Testimonials</h2>
          <p>Magnam dolores commodi suscipit eum quidem consectetur velit</p>
        </div>

        <div class="testimonials-slider swiper-container" data-aos="fade-up" data-aos-delay="100">
          <div class="swiper-wrapper">

            <div class="swiper-slide">
              <div class="testimonial-wrap">
                <div class="testimonial-item">
                  <img src="{{ url_for('static', filename='img/testimonials/testimonials-1.jpg') }}" class="testimonial-img" alt="">
                  <h3>Saul Goodman</h3>
                  <h4>Ceo &amp; Founder</h4>
                  <p>
                    <i class="bx bxs-quote-alt-left quote-icon-left"></i>
                    Proin iaculis purus consequat sem cure digni ssim donec porttitora entum suscipit rhoncus. Accusantium quam, ultricies eget id, aliquam eget nibh et. Maecen aliquam, risus at semper.
                    <i class="bx bxs-quote-alt-right quote-icon-right"></i>
                  </p>
                </div>
              </div>
            </div><!-- End testimonial item -->

            <div class="swiper-slide">
              <div class="testimonial-wrap">
                <div class="testimonial-item">
                  <img src="{{ url_for('static', filename='img/testimonials/testimonials-2.jpg') }}" class="testimonial-img" alt="">
                  <h3>Sara Wilsson</h3>
                  <h4>Designer</h4>
                  <p>
                    <i class="bx bxs-quote-alt-left quote-icon-left"></i>
                    Export tempor illum tamen malis malis eram quae irure esse labore quem cillum quid cillum eram malis quorum velit fore eram velit sunt aliqua noster fugiat irure amet legam anim culpa.
                    <i class="bx bxs-quote-alt-right quote-icon-right"></i>
                  </p>
                </div>
              </div>
            </div><!-- End testimonial item -->

            <div class="swiper-slide">
              <div class="testimonial-wrap">
                <div class="testimonial-item">
                  <img src="{{ url_for('static', filename='img/testimonials/testimonials-3.jpg') }}" class="testimonial-img" alt="">
                  <h3>Jena Karlis</h3>
                  <h4>Store Owner</h4>
                  <p>
                    <i class="bx bxs-quote-alt-left quote-icon-left"></i>
                    Enim nisi quem export duis labore cillum quae magna enim sint quorum nulla quem veniam duis minim tempor labore quem eram duis noster aute amet eram fore quis sint minim.
                    <i class="bx bxs-quote-alt-right quote-icon-right"></i>
                  </p>
                </div>
              </div>
            </div><!-- End testimonial item -->

            <div class="swiper-slide">
              <div class="testimonial-wrap">
                <div class="testimonial-item">
                  <img src="{{ url_for('static', filename='img/testimonials/testimonials-4.jpg') }}" class="testimonial-img" alt="">
                  <h3>Matt Brandon</h3>
                  <h4>Freelancer</h4>
                  <p>
                    <i class="bx bxs-quote-alt-left quote-icon-left"></i>
                    Fugiat enim eram quae cillum dolore dolor amet nulla culpa multos export minim fugiat minim velit minim dolor enim duis veniam ipsum anim magna sunt elit fore quem dolore labore illum veniam.
                    <i class="bx bxs-quote-alt-right quote-icon-right"></i>
                  </p>
                </div>
              </div>
            </div><!-- End testimonial item -->

            <div class="swiper-slide">
              <div class="testimonial-wrap">
                <div class="testimonial-item">
                  <img src="{{ url_for('static', filename='img/testimonials/testimonials-5.jpg') }}" class="testimonial-img" alt="">
                  <h3>John Larson</h3>
                  <h4>Entrepreneur</h4>
                  <p>
                    <i class="bx bxs-quote-alt-left quote-icon-left"></i>
                    Quis quorum aliqua sint quem legam fore sunt eram irure aliqua veniam tempor noster veniam enim culpa labore duis sunt culpa nulla illum cillum fugiat legam esse veniam culpa fore nisi cillum quid.
                    <i class="bx bxs-quote-alt-right quote-icon-right"></i>
                  </p>
                </div>
              </div>
            </div><!-- End testimonial item -->

          </div>
          <div class="swiper-pagination"></div>
        </div>

      </div>
    </section><!-- End Testimonials Section -->


    {% include "sections/faq.html" %}

        
    <div class="bottom_btns">
      <a href="{{ url_for('quote.quote_page') }}">Get A Quote</a>
      <a href="{{ url_for('main.portfolio') }}">See Portfolio</a>
    </div>
  </main><!-- End #main -->

  <!-- ======= Footer ======= -->
  <footer id="footer">
    <div class="container">
      <div class="row d-flex align-items-center">
        <div class="col-lg-6 text-lg-left text-center">
          <div class="copyright">
            &copy; Copyright <strong>Faiz4work</strong>. All Rights Reserved
          </div>
          <div class="credits">
            Designed by <a href="#">Faiz Ahmed</a>
          </div>
        </div>
      </div>
    </div>
  </footer><!-- End Footer -->

  <a href="#" class="back-to-top d-flex align-items-center justify-content-center"><i class="bi bi-arrow-up-short"></i></a>

{% endblock %}

portfolio_site/templates/layout.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta content="width=device-width, initial-scale=1.0" name="viewport">

  <title>Complete website and scraping solutions - Faiz4work</title>
  <meta content="" name="description">
  <meta content="" name="keywords">

  <!-- Jquery CDN -->
  <script src="https://code.jquery.com/jquery-3.6.0.js" integrity="sha256-H+K7U5CnXl1h5ywQfKtSj8PCmoN9aaq30gDh27Xc0jk=" crossorigin="anonymous"></script>

  <!-- Favicons -->
  <link href="{{ url_for('static', filename='img/favicon.png') }}" rel="icon">

  <!-- Google Fonts -->
  <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Raleway:300,300i,400,400i,500,500i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i" rel="stylesheet">

  <!-- Vendor CSS Files -->
  <link href="{{ url_for('static', filename='vendor/aos/aos.css') }}" rel="stylesheet">
  <link href="{{ url_for('static', filename='vendor/bootstrap/css/bootstrap.min.css') }}" rel="stylesheet">
  <link href="{{ url_for('static', filename='vendor/bootstrap-icons/bootstrap-icons.css') }}" rel="stylesheet">
  <link href="{{ url_for('static', filename='vendor/boxicons/css/boxicons.min.css') }}" rel="stylesheet">
  <link href="{{ url_for('static', filename='vendor/glightbox/css/glightbox.min.css') }}" rel="stylesheet">
  <link href="{{ url_for('static', filename='vendor/remixicon/remixicon.css') }}" rel="stylesheet">
  <link href="{{ url_for('static', filename='vendor/swiper/swiper-bundle.min.css') }}" rel="stylesheet">

  <!-- Template Main CSS File -->
  <link href="{{ url_for('static', filename='css/style.css') }}" rel="stylesheet">

  <!-- Custom css file -->
  <link href="{{ url_for('static', filename='css/custom_style.css') }}" rel="stylesheet">

</head>

<body>

 {% include "sections/header.html" %}


  {% block body %}
  {% endblock %}


  <!-- Vendor JS Files -->
  <script src="{{ url_for('static', filename='vendor/aos/aos.js') }}"></script>
  <script src="{{ url_for('static', filename='vendor/bootstrap/js/bootstrap.bundle.min.js') }}"></script>
  <script src="{{ url_for('static', filename='vendor/glightbox/js/glightbox.min.js') }}"></script>
  <script src="{{ url_for('static', filename='vendor/isotope-layout/isotope.pkgd.min.js') }}"></script>
  <script src="{{ url_for('static', filename='vendor/purecounter/purecounter.js') }}"></script>
  <script src="{{ url_for('static', filename='vendor/swiper/swiper-bundle.min.js') }}"></script>

  <!-- Template Main JS File -->
  <script src="{{ url_for('static', filename='js/main.js') }}"></script>
</body>

</html>

portfolio_site/templates/quote/quote_form.html
{% extends "layout.html" %}

{% block body %}
<div class="form_div">
    <h1>Quotation Form</h1>
    <h4>Tell us about your project so we can suggest you a reasonable price and timeframe.</h4>


        <label for="pType">Please choose project type:</label>
        <select name="pType" id="pType">
            <option value="0">--Select--</option>
            <option value="1">Website Development</option>
            <option value="2">Web Scraping</option>
            <option value="3">A.P.I Development</option>
            <option value="4">E-Commerce Store</option>
        </select>
    
        {% include "quote/web_dev_form.html" %}
</div>


<link rel="stylesheet" href="{{ url_for('static', filename='css/quote.css') }}">
<script src="{{ url_for('static', filename='js/quote.js') }}"></script>
{% endblock %}

portfolio_site/templates/sections/contact.html
{% extends "layout.html" %}  

{% block body %}
  <!-- ======= Contact Section ======= -->
  <section id="contact" class="contact my-5">
    <div class="container">

      <div class="section-title" data-aos="fade-up">
        <h2>Contact Us</h2>
      </div>

      <div class="row">



        <div class="col-lg-4 col-md-6 mt-4 mt-md-0" data-aos="fade-up" data-aos-delay="200">
         <div class="contact-about">
            <div class="social-links">
              <a href="#" class="twitter"><i class="bi bi-twitter"></i></a>
              <a href="#" class="facebook"><i class="bi bi-facebook"></i></a>
              <a href="#" class="instagram"><i class="bi bi-instagram"></i></a>
              <a href="#" class="linkedin"><i class="bi bi-linkedin"></i></a>
            </div>
          </div>
          <div class="info">
            <div>
              <i class="ri-map-pin-line"></i>
              <p>Karachi, Pakistan</p>
            </div>

            <div>
              <i class="ri-mail-send-line"></i>
              <p>admin@faiz4work.com</p>
            </div>

            <div>
              <i class="ri-phone-line"></i>
              <p>+92 3020230479</p>
            </div>

          </div>
        </div>

        <div class="col-lg-8 col-md-12" data-aos="fade-up" data-aos-delay="300">
          <form action="{{ url_for('main.email') }}" method="post" role="form" 
                                  class="php-email-form" id="email-form">
            <div class="form-group">
              <input type="text" name="name" class="form-control" id="name" placeholder="Your Name" required>
            </div>
            <div class="form-group">
              <input type="email" class="form-control" name="email" id="email" placeholder="Your Email" required>
            </div>
            <div class="form-group">
              <input type="text" class="form-control" name="subject" id="subject" placeholder="Subject" required>
            </div>
            <div class="form-group">
              <textarea class="form-control" name="message" rows="5" placeholder="Message" 
              id="message" required></textarea>
            </div>
            <div class="my-3">
              <div class="loading">Loading</div>
              <div class="error-message"></div>
              <div class="sent-message">Your message has been sent. Thank you!</div>
            </div>
            <div class="text-center">
              <button type="submit" id="submit-button">Send Message</button>
              <img src="static/img/animations/fidget-spinner.gif" alt="loding gif" id="loading_gif"
              style="display: none;">
            </div>
          </form>
        </div>

      </div>

    </div>
  </section><!-- End Contact Section -->

  <script src="{{ url_for('static', filename='js/email.js') }}"></script>
{% endblock %}

portfolio_site/templates/sections/header.html
 <!-- ======= Header ======= -->
 <header id="header" class="fixed-top d-flex align-items-center">
    <div class="container d-flex align-items-center justify-content-between">

      <div class="logo">
        <h1><a href="/">Faiz4work</a></h1>
        <!-- Uncomment below if you prefer to use an image logo -->
        <!-- <a href="/"><img src="static/img/logo.png" alt="website logo" style="width: 200px; height:200px;"></a> -->
      </div>

      <nav id="navbar" class="navbar">
        <ul>
          <li><a class="nav-link scrollto active" href="/">Home</a></li>
          <!-- <li><a class="nav-link scrollto" href="#about">About</a></li> -->
          <!-- <li><a class="nav-link scrollto" href="#services">Services</a></li> -->
          <div class="dropdown">
            <a class="dropbtn" href="#services">Services <span><i class="bi bi-caret-down-fill"></i></span></a>
            
            <div class="dropdown-content">
              <a href="{{ url_for('main.web_development') }}">Web Development</a>
              <a href="{{ url_for('main.web_scraping') }}">Web Scraping</a>
              <a href="{{ url_for('main.api') }}">API Development</a>
              <a href="{{ url_for('main.ecommerce') }}">E-Commerce Management</a>
            </div>
          </div> 
          <li><a class="nav-link scrollto " href="{{url_for('main.portfolio')}}">Portfolio</a></li>
          <li><a class="nav-link scrollto" href="{{ url_for('main.contact') }}">Contact</a></li>
          <li><a class="getstarted scrollto" href="{{ url_for('quote.quote_page') }}">Get A Quote</a></li>
        </ul>
        <i class="bi bi-list mobile-nav-toggle"></i>
      </nav><!-- .navbar -->

    </div>
  </header><!-- End Header -->


  <style>


/* The container <div> - needed to position the dropdown content */
.dropdown {
  position: relative;
  display: inline-block;
}

.dropdown-content {
  display: none;
  position: absolute;
  background-color: #f1f1f1;
  min-width: 160px;
  box-shadow: 0px 8px 16px 0px rgba(0,0,0,0.2);
  z-index: 1;
}

/* Links inside the dropdown */
.dropdown-content a {
  color: black;
  padding: 12px 16px;
  text-decoration: none;
  display: block;
}

/* Change color of dropdown links on hover */
.dropdown-content a:hover {background-color: #ddd;}

/* Show the dropdown menu on hover */
.dropdown:hover .dropdown-content {display: block;}

/* Change the background color of the dropdown button when the dropdown content is shown */
/*.dropdown:hover .dropbtn {background-color: #3e8e41;}  */
  </style>

portfolio_site/templates/sections/layout.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta content="width=device-width, initial-scale=1.0" name="viewport">

  <title>Complete website and scraping solutions - Faiz4work</title>
  <meta content="" name="description">
  <meta content="" name="keywords">

  <!-- Favicons -->
  <link href="{{ url_for('static', filename='img/favicon.png') }}" rel="icon">

  <!-- Google Fonts -->
  <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Raleway:300,300i,400,400i,500,500i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i" rel="stylesheet">

  <!-- Vendor CSS Files -->
  <link href="{{ url_for('static', filename='vendor/aos/aos.css') }}" rel="stylesheet">
  <link href="{{ url_for('static', filename='vendor/bootstrap/css/bootstrap.min.css') }}" rel="stylesheet">
  <link href="{{ url_for('static', filename='vendor/bootstrap-icons/bootstrap-icons.css') }}" rel="stylesheet">
  <link href="{{ url_for('static', filename='vendor/boxicons/css/boxicons.min.css') }}" rel="stylesheet">
  <link href="{{ url_for('static', filename='vendor/glightbox/css/glightbox.min.css') }}" rel="stylesheet">
  <link href="{{ url_for('static', filename='vendor/remixicon/remixicon.css') }}" rel="stylesheet">
  <link href="{{ url_for('static', filename='vendor/swiper/swiper-bundle.min.css') }}" rel="stylesheet">

  <!-- Template Main CSS File -->
  <link href="{{ url_for('static', filename='css/style.css') }}" rel="stylesheet">

</head>

<body>

  <!-- ======= Header ======= -->
  <header id="header" class="fixed-top d-flex align-items-center">
    <div class="container d-flex align-items-center justify-content-between">

      <div class="logo">
        <h1><a href="/">Faiz4work</a></h1>
        <!-- Uncomment below if you prefer to use an image logo -->
        <!-- <a href="/"><img src="static/img/logo.png" alt="website logo" style="width: 200px; height:200px;"></a> -->
      </div>

      <nav id="navbar" class="navbar">
        <ul>
          <li><a class="nav-link scrollto active" href="/">Home</a></li>
          <li><a class="nav-link scrollto" href="#about">About</a></li>
          <li><a class="nav-link scrollto" href="#services">Services</a></li>
          <li><a class="nav-link scrollto " href="{{url_for('main.portfolio')}}">Portfolio</a></li>
          <li><a class="nav-link scrollto" href="#contact">Contact</a></li>
          <li><a class="getstarted scrollto" href="#">Get Started</a></li>
        </ul>
        <i class="bi bi-list mobile-nav-toggle"></i>
      </nav><!-- .navbar -->

    </div>
  </header><!-- End Header -->

  {% block body %}
  {% endblock %}


  <!-- Vendor JS Files -->
  <script src="{{ url_for('static', filename='vendor/aos/aos.js') }}"></script>
  <script src="{{ url_for('static', filename='vendor/bootstrap/js/bootstrap.bundle.min.js') }}"></script>
  <script src="{{ url_for('static', filename='vendor/glightbox/js/glightbox.min.js') }}"></script>
  <script src="{{ url_for('static', filename='vendor/isotope-layout/isotope.pkgd.min.js') }}"></script>
  <script src="{{ url_for('static', filename='vendor/purecounter/purecounter.js') }}"></script>
  <script src="{{ url_for('static', filename='vendor/swiper/swiper-bundle.min.js') }}"></script>

  <!-- Template Main JS File -->
  <script src="{{ url_for('static', filename='js/main.js') }}"></script>
</body>

</html>

portfolio_site/templates/sections/services_page/api.html
{% extends "layout.html" %}
{% block body %}

<h1>API</h1>
<h1>API</h1>
<h1>API</h1>
<h1>API</h1>
<h1>API</h1>


{% endblock body %}

portfolio_site/templates/sections/services_page/ecommerce.html
{% extends "layout.html" %}
{% block body %}

<h1>E-Commerce</h1>
<h1>E-Commerce</h1>
<h1>E-Commerce</h1>
<h1>E-Commerce</h1>
<h1>E-Commerce</h1>


{% endblock body %}

portfolio_site/templates/sections/services_page/services.html
 <!-- ======= Services Section ======= -->
 <section id="services" class="services">
    <div class="container">

      <div class="section-title" data-aos="fade-up">
        <h2>Services</h2>
        <p>Below are the main services that i am offering and you can also ask if 
          you have some special requirements.</p>
      </div>

      <div class="row">
        <div class="col-md-6 col-lg-3 d-flex align-items-stretch mb-5 mb-lg-0">
          <div class="icon-box" data-aos="fade-up" data-aos-delay="100">
            <div class="icon"><i class="bx bx-world"></i></div>
            <h4 class="title"><a href="#">Web Development</a></h4>
            <p class="description">Custom functionality website, Bussiness website, portfolio site,
                        Private company sites, see <a class="btn btn-outline-info btn-sm" 
                        href="{{ url_for('main.web_development') }}"
                        onmouseover="this.style.color='white';"
                        onmouseout="this.style.color='blue';">details page</a></p>
          </div>
        </div>

        <div class="col-md-6 col-lg-3 d-flex align-items-stretch mb-5 mb-lg-0">
          <div class="icon-box" data-aos="fade-up" data-aos-delay="200">
            <div class="icon"><i class="bx bx-file"></i></div>
            <h4 class="title"><a href="">E-Commerce store</a></h4>
            <p class="description">Build your bussiness with me. fully funtional eCommerce store
                                    with payments and other usefull functionalities. see
                                    <a class="btn btn-outline-info btn-sm" 
                                    href="{{ url_for('main.ecommerce') }}"
                                    onmouseover="this.style.color='white';"
                                    onmouseout="this.style.color='blue';">details page</a></p>
          </div>
        </div>

        <div class="col-md-6 col-lg-3 d-flex align-items-stretch mb-5 mb-lg-0">
          <div class="icon-box" data-aos="fade-up" data-aos-delay="300">
            <div class="icon"><i class="bx bx-tachometer"></i></div>
            <h4 class="title"><a href="">Web Scraping & Automation</a></h4>
            <p class="description">Get usefull data from any website. full products specification.
                                   Get and upload it to your site automatically. see
                                   <a class="btn btn-outline-info btn-sm" 
                                   href="{{ url_for('main.web_scraping') }}"
                                   onmouseover="this.style.color='white';"
                                   onmouseout="this.style.color='blue';">details page</a></p>
          </div>
        </div>

        <div class="col-md-6 col-lg-3 d-flex align-items-stretch mb-5 mb-lg-0">
          <div class="icon-box" data-aos="fade-up" data-aos-delay="400">
            <div class="icon"><i class='bx bx-shape-circle'></i></div>
            
            <h4 class="title"><a href="">API (Application Programming Interface)</a></h4>
            <p class="description">Link third party services like payment integration, social media login,
                                   live news feeds, match scores and much more. see 
                                   <a class="btn btn-outline-info btn-sm" 
                                   href="{{ url_for('main.api') }}"
                                   onmouseover="this.style.color='white';"
                                   onmouseout="this.style.color='blue';">details page</a></p>
          </div>
        </div>

      </div>

    </div>
  </section><!-- End Services Section -->

portfolio_site/templates/sections/services_page/web_development.html
{% extends "layout.html" %}
{% block body %}

<h1>Website development</h1>
<h1>Website development</h1>
<h1>Website development</h1>
<h1>Website development</h1>

{% endblock body %}